#!/bin/bash

if [ -d ~/zookeeper ]
then
    echo "Found Zookeeper installation."
else   
    echo "Installing Zookeeper"
    wget -O /tmp/zookeeper.tar.gz http://mirrors.enquira.co.uk/apache/zookeeper/zookeeper-3.3.6/zookeeper-3.3.6.tar.gz
    tar -zxf /tmp/zookeeper.tar.gz -C /tmp/
    mv /tmp/zookeeper  ~/zookeeper
fi
cp -a zookeeper/zoo.cfg ~/zookeeper/conf/zoo.cfg
[ -d ~/data/zookeeper_data ] ||
    mkdir -p ~/data/zookeeper_data


